language: julia
os:
  - linux
  - osx
julia:
  - 1.1
  - nightly
matrix:
    allow_failures:
        - julia: nightly
notifications:
  email: false

before_script:
  - julia --color=yes -e 'using Pkg;Pkg.Registry.add(RegistrySpec(url="https://github.com/vincentcp/FrameFunRegistry"));'
  - julia --color=yes -e 'using Pkg;Pkg.Registry.add(RegistrySpec(url="https://github.com/JuliaRegistries/General"));'

after_success:
  - julia --project=coverage/ --color=yes coverage/coverage.jl

# jobs:
#     include:
#         - stage: "Documentation"
#           julia: 1.1
#           os: linux
#           script:
#             - julia --project=docs/ --color=yes docs/make.jl deploy
#           after_success: skip
