language: julia
os:
  - linux
  - osx
julia:
  - nightly
  - 1.0
matrix:
    allow_failures:
        - julia: nightly
notifications:
    email: false
after_success:
  - julia -e 'using Pkg;cd(Pkg.dir("BasisFunctions")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder()); Codecov.submit(process_folder())'
